### PR TITLE
Renames frontity.php to wp-pwa.php to avoid conflicts

### LINKED ISSUE #76: Fix plugin filename to avoid conflicts on update

### PR DESCRIPTION
**Pull request by orballo**
fixes https://github.com/frontity/wp-plugin/issues/76

### CODE REVIEW

**Comment by orballo** [comment]
@luisherranz ready for review 😄

**Review by luisherranz — APPROVED** [review]
Tested in local and everything seems fine. Let's hope there are no more problems this time!

**Comment by luisherranz** [comment]
@orballo merged, you can release it 👍

**Pull request merged**
